src/main/java/bg/tu/sofia/model/Blobs.java
package bg.tu.sofia.model;

import com.sun.org.apache.xerces.internal.impl.dv.util.Base64;

import javax.persistence.*;
import java.util.Arrays;
import java.util.Date;
import java.util.Objects;

@Entity
public class Blobs {
    private Integer id;
    private String filename;
    private String contentType;
    private Integer filesize;
    private byte[] content;
    private Date createdDate;

    @Id
    @GeneratedValue(generator = "blobs_id_seq")
    @SequenceGenerator(sequenceName = "blobs_id_seq", name = "blobs_id_seq", schema = "public", allocationSize = 1, initialValue = 1)
    @Column(name = "id")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Basic
    @Column(name = "filename")
    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Basic
    @Column(name = "content_type")
    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    @Basic
    @Column(name = "filesize")
    public Integer getFilesize() {
        return filesize;
    }

    public void setFilesize(Integer filesize) {
        this.filesize = filesize;
    }

    @Basic
    @Column(name = "content")
    public byte[] getContent() {
        return content;
    }

    public void setContent(byte[] content) {
        this.content = content;
    }

    @Basic
    @Column(name = "created_date")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Transient
    public String getEncodedContent() {
        return Base64.encode(this.content);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Blobs blobs = (Blobs) o;
        return Objects.equals(id, blobs.id) &&
                Objects.equals(filename, blobs.filename) &&
                Objects.equals(contentType, blobs.contentType) &&
                Objects.equals(filesize, blobs.filesize) &&
                Arrays.equals(content, blobs.content) &&
                Objects.equals(createdDate, blobs.createdDate);
    }

    @Override
    public int hashCode() {

        int result = Objects.hash(id, filename, contentType, filesize, createdDate);
        result = 31 * result + Arrays.hashCode(content);
        return result;
    }
}

src/main/java/bg/tu/sofia/model/Role.java
package bg.tu.sofia.model;

import javax.persistence.*;
import java.util.Objects;

/**
 * Created by denislav.veizov on 4.3.2018 г..
 */
@Entity
@Table(name = "role", schema = "public")
@Cacheable(value = false)
public class Role {
    private Integer id;
    private String name;
    private boolean containByUser;

    @Id
    @GeneratedValue(generator = "role_id_seq")
    @SequenceGenerator(sequenceName = "role_id_seq", name = "role_id_seq", schema = "public", allocationSize = 1, initialValue = 1)
    @Column(name = "id")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Basic
    @Column(name = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Transient
    public boolean isContainByUser() {
        return containByUser;
    }

    public void setContainByUser(boolean containByUser) {
        this.containByUser = containByUser;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Role role = (Role) o;

        if (!Objects.equals(id, role.id)) return false;
        if (name != null ? !name.equals(role.name) : role.name != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = (id != null ? id.hashCode() : 0);;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        return result;
    }
}

src/main/java/bg/tu/sofia/controller/CreateBookController.java
package bg.tu.sofia.controller;

import bg.tu.sofia.model.Blobs;
import bg.tu.sofia.model.Book;
import bg.tu.sofia.model.BookCategory;
import bg.tu.sofia.model.Language;
import bg.tu.sofia.service.BookCategoryService;
import bg.tu.sofia.service.BookService;
import bg.tu.sofia.service.LanguageService;
import bg.tu.sofia.utils.FileUtils;
import bg.tu.sofia.utils.Utils;
import bg.tu.sofia.validator.BookValidator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.propertyeditors.CustomDateEditor;
import org.springframework.context.MessageSource;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.util.CollectionUtils;
import org.springframework.util.StringUtils;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import javax.servlet.http.HttpServletRequest;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.*;


/**
 * Created by denislav.veizov on 30.1.2018 г..
 */
@Controller
@RequestMapping("/admin")
public class CreateBookController {
    private static Logger LOG = LoggerFactory.getLogger(CreateBookController.class);
    private static final Integer MAX_BOOK_COVER_FILE_SIZE = 1_048_576; //1 MB
    private static final Integer MAX_BOOKS_FOLDER_SIZE = 524_288_000; //500 MB
    private static final Integer MIN_BYTE_ARRAY_LENGTH = 1;
    private static final Integer PDF_FILES_PER_ITERATION = 5;
    private static final String DEFAULT_CATEGORY = "Other";

    private Boolean inProgress = false;
    private Integer progress = 0;

    @Autowired
    private MessageSource messageSource;

    @Autowired
    private BookService bookService;

    @Autowired
    private BookValidator bookValidator;

    @Autowired
    private BookCategoryService categoryService;

    @Autowired
    private LanguageService languageService;

    @RequestMapping(value = "/create-book", method = RequestMethod.GET)
    public String createBook(HttpServletRequest request, Model model, @RequestParam(value = "id", required = false) Integer bookID) {
        Book book = bookService.findById(bookID);

        if (!model.containsAttribute("book") && book == null) {
            request.getSession().setAttribute("coverImage", new Blobs());
            request.getSession().setAttribute("bookFile", new Blobs());
            model.addAttribute("book", new Book());
        }

        if (!model.containsAttribute("book") && book != null) {
            request.getSession().setAttribute("coverImage", book.getCover() != null ? book.getCover() : new Blobs());
            request.getSession().setAttribute("bookFile", book.getFile() != null ? book.getFile() : new Blobs());
            model.addAttribute("book", book);
        }

        List<BookCategory> categories = categoryService.findAll();
        model.addAttribute("categories", categories);

        List<Language> languages = languageService.findAll();
        model.addAttribute("languages", languages);
        return "admin/create-book";
    }

    @RequestMapping(value = "/create-book", method = RequestMethod.POST)
    public String createBook(RedirectAttributes redirectAttributes, HttpServletRequest request, @ModelAttribute Book book, BindingResult bindingResult,
                             @RequestParam("imageFile") MultipartFile imageFileRequest,
                             @RequestParam("bookFile") MultipartFile bookFileRequest) {

        try {
            Blobs coverImage = (Blobs) request.getSession().getAttribute("coverImage");
            fillBlob(imageFileRequest, coverImage);
            book.setCover(coverImage);

            Blobs bookFile = (Blobs) request.getSession().getAttribute("bookFile");
            fillBlob(bookFileRequest, bookFile);
            book.setFile(bookFile);
        } catch (IOException e) {
            LOG.error(e.getMessage(), e);
            throw new RuntimeException(e.getMessage(), e);
        }

        bookValidator.validate(book, bindingResult);
        if (bindingResult.hasErrors()) {
            redirectAttributes.addFlashAttribute("org.springframework.validation.BindingResult.book", bindingResult);
            redirectAttributes.addFlashAttribute("book", book);

            if (book.getId() != null)
                redirectAttributes.addAttribute("id", book.getId());

            return "redirect:/admin/create-book";
        } else {
            byte[] bookCoverContent = book.getCover().getContent();
            if (null == bookCoverContent || MIN_BYTE_ARRAY_LENGTH > bookCoverContent.length)
                book.setCover(null);
            Date currentDate = new Date();
            if (Objects.isNull(book.getId()))
                book.setCreatedDate(currentDate);
            else {
                Book databaseBook = bookService.findById(book.getId());
                book.setCreatedDate(Objects.nonNull(databaseBook) ? databaseBook.getCreatedDate() : null);
            }

            book.setLastUpdate(currentDate);
            book.setNumberOfPages(Utils.getNumberOfPages(book.getFile().getContent()));
            bookService.save(book);

            request.getSession().removeAttribute("coverImage");
            request.getSession().removeAttribute("bookFile");
            return "redirect:/books";
        }
    }

    @RequestMapping(value = "/edit-book", method = RequestMethod.GET)
    public String editBook(Model model,
                           RedirectAttributes redirectAttributes,
                           HttpServletRequest request,
                           @RequestParam("bookID") Integer bookID) {
        Book book = bookService.findById(bookID);
        if (Objects.nonNull(book))
            redirectAttributes.addFlashAttribute("book", book);

        return "redirect:/admin/create-book";
    }

    @RequestMapping("/validate-uploaded-file")
    @ResponseBody
    public List<String> validateUploadedBookCover(@RequestParam("fileName") String fileName, @RequestParam("size") Integer size) {
        List<String> errors = new ArrayList<String>();
        String format = fileName.substring(fileName.lastIndexOf(".", fileName.length()));
        if (!format.equalsIgnoreCase(".jpg") && !format.equalsIgnoreCase(".png")) {
            String message = messageSource.getMessage("cover.upload.valid", null, LocaleContextHolder.getLocale());
            errors.add(message);
        }
        if (MAX_BOOK_COVER_FILE_SIZE < size) {
            String message = messageSource.getMessage("cover.upload.size.valid", null, LocaleContextHolder.getLocale());
            errors.add(message);
        }
        return errors;
    }

    @RequestMapping("/validate-uploaded-book-file")
    @ResponseBody
    public List<String> validateUploadedBookFile(@RequestParam("fileName") String fileName) {
        List<String> errors = new ArrayList<String>();
        String format = fileName.substring(fileName.lastIndexOf(".", fileName.length()));
        if (!format.equalsIgnoreCase(".pdf")) {
            String message = messageSource.getMessage("pdf.upload.valid", null, LocaleContextHolder.getLocale());
            errors.add(message);
        }
        return errors;
    }

    private void fillBlob(@RequestParam("imageFile") MultipartFile imageFile, Blobs blobs) throws IOException {
        if (null != imageFile && !StringUtils.isEmpty(imageFile.getOriginalFilename())) {
            blobs.setFilename(imageFile.getOriginalFilename());
            blobs.setContentType(imageFile.getContentType());
            blobs.setContent(imageFile.getBytes());
            blobs.setCreatedDate(new Date());
            blobs.setFilesize((int) imageFile.getSize());
        }
    }

    @RequestMapping(value = "/create-books-folder", method = RequestMethod.GET)
    public String createBooksFromFolder(HttpServletRequest request, Model model) {
        model.addAttribute("inProgress", inProgress);
        return "admin/create-books-folder";
    }

    @RequestMapping(value = "/create-books-folder", method = RequestMethod.POST)
    public String createBooksFromFolder(Model model, @RequestParam("folder") String folderPath) {
        if (!inProgress) {

            inProgress = true;
            progress = 0;

            try {
                Path path = Paths.get(folderPath.trim());
                long folderSize = FileUtils.folderSize(path.toFile());

                if (MAX_BOOKS_FOLDER_SIZE < folderSize)
                    throw new RuntimeException("Folder size is greater than 500 MB ! Current size: " + ((folderSize / 1024) / 1024) + " MB");

                int pdfFilesCount = Math.toIntExact(Files.walk(path)
                        .filter(p -> p.toFile().isFile())
                        .filter(p -> p.toFile().getName().toLowerCase().endsWith(".pdf"))
                        .count());

                if (pdfFilesCount > 0) {
                    BookCategory other = categoryService.findByNameEn(DEFAULT_CATEGORY);

                    Map<String, Integer> importedBooks = new HashMap<>();
                    Map<String, Integer> notImportedBooks = new HashMap<>();

                    int maxIterations = (pdfFilesCount / PDF_FILES_PER_ITERATION) + 1;
                    for (int skip, i = 0; i < maxIterations; i++) {
                        skip = i * PDF_FILES_PER_ITERATION;
                        List<File> filePart = FileUtils.getPdfFiles(path, skip, PDF_FILES_PER_ITERATION);
                        for (int j = 0; j < filePart.size(); j++) {
                            File file = filePart.get(j);

src/main/webapp/WEB-INF/view/admin/books-folder-content.jsp
<%--
  Created by IntelliJ IDEA.
  User: denislav.veizov
  Date: 23.1.2018 г.
  Time: 16:23
  To change this template use File | Settings | File Templates.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="custom" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>

<c:choose>
    <c:when test="${alreadyStarted eq true}">
        Процесът вече е стартиран....
    </c:when>
    <c:otherwise>
        <div class="row">
            <div class="col s12">
                <ul class="tabs ">
                    <li class="tab col s6">
                        <a href="#new-book"><spring:message code="label.new.books"/></a>
                    </li>
                    <li class="tab col s6">
                        <a href="#existing-books"><spring:message code="label.existing.books"/></a>
                    </li>
                </ul>
            </div>
            <div id="new-book" class="col s12 mT2em">
                <c:if test="${empty importedBooks}">
                    <div>
                        <div class="alert alert-info info-tab align-center">
                            <spring:message code="empty.list"/>
                        </div>
                    </div>
                </c:if>
                <c:if test="${not empty importedBooks}">
                    <div class="mB-5px font-size-15"><spring:message code="table.records.count"/>:
                        <span class="bold">${importedBooks.size()}</span>
                    </div>
                    <table class="responsive-table striped">
                        <thead>
                        <tr>
                            <th class="w5"><spring:message code="table.number"/></th>
                            <th><spring:message code="table.name"/></th>
                            <th class="w10"><spring:message code="table.size"/></th>
                            <th class="w10"><spring:message code="table.add"/></th>
                        </tr>
                        </thead>
                        <tbody>
                        <c:forEach var="book" items="${importedBooks}" varStatus="status">
                            <tr>
                                <td class="w5">${status.count}</td>
                                <td><c:out value="${book.key}"/></td>
                                <td class="w10">
                                    <fmt:formatNumber type="number" maxFractionDigits="2" value="${(book.value / 1024)/1024}" /> MB
                                </td>
                                <td class="align-center w10">
                                    <img class="img24" src="<c:url value="/resources/images/success.png"/>"/>
                                </td>
                            </tr>
                        </c:forEach>
                        </tbody>
                    </table>
                </c:if>
            </div>
            <div id="existing-books" class="col s12 mT2em">
                <c:if test="${empty notimported}">
                    <div>
                        <div class="alert alert-info info-tab align-center">
                            <spring:message code="empty.list"/>
                        </div>
                    </div>
                </c:if>
                <c:if test="${not empty notimported}">
                    <div class="mB-5px font-size-15"><spring:message code="table.records.count"/>:
                        <span class="bold">${notimported.size()}</span>
                    </div>
                    <table class="responsive-table striped">
                        <thead>
                        <tr>
                            <th class="w5"><spring:message code="table.number"/></th>
                            <th><spring:message code="table.name"/></th>
                            <th class="w10"><spring:message code="table.size"/></th>
                            <th class="w10"><spring:message code="table.add"/></th>
                        </tr>
                        </thead>
                        <tbody>
                        <c:forEach var="book" items="${notimported}" varStatus="status">
                            <tr>
                                <td class="w5">${status.count}</td>
                                <td><c:out value="${book.key}"/></td>
                                <td class="w10">
                                    <fmt:formatNumber type="number" maxFractionDigits="2" value="${(book.value / 1024)/1024}"/> MB
                                </td>
                                <td class="align-center w10">
                                    <img class="img24" src="<c:url value="/resources/images/error.png"/>"/>
                                </td>
                            </tr>
                        </c:forEach>
                        </tbody>
                    </table>
                </c:if>
            </div>
        </div>
    </c:otherwise>
</c:choose>
<script>
    $(document).ready(function(){
        $('.tabs').tabs();
    });
</script>

src/main/webapp/WEB-INF/view/admin/categories_table.jsp
<%--
  Created by IntelliJ IDEA.
  User: denislav.veizov
  Date: 23.1.2018 г.
  Time: 16:23
  To change this template use File | Settings | File Templates.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="custom" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>



<c:if test="${empty categories}">
    <div>
        <div class="alert alert-info info-tab align-center">
            <spring:message code="empty.table"/>
        </div>
    </div>
</c:if>

<c:if test="${not empty categories}">
    <table class="responsive-table striped">
        <thead>
        <tr>
            <th class="w5"><spring:message code="table.number"/></th>
            <th><spring:message code="table.name"/></th>
            <th class=""><spring:message code="table.name.en"/></th>
            <th class="w50px"><spring:message code="table.options"/></th>
        </tr>
        </thead>
        <tbody>
        <c:forEach var="category" items="${categories}" varStatus="status">
            <tr>
                <td class="w5">${status.count}</td>
                <td>${category.name}</td>
                <td>${category.nameEn}</td>
                <td class="w50px">
                    <a id="delete-category-btn" class="mR5px" href="javascript:void(0)"
                       title="<spring:message code="btn.delete"/>" data-id="${category.id}" >
                        <img class="img24" src="<c:url value="/resources/images/delete-icon.png"/>"/>
                    </a>
                </td>
            </tr>
        </c:forEach>
        </tbody>
    </table>
</c:if>

src/main/webapp/WEB-INF/view/admin/create-book.jsp
<%--
  Created by IntelliJ IDEA.
  User: denislav.veizov
  Date: 23.1.2018 г.
  Time: 16:23
  To change this template use File | Settings | File Templates.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="../common/header.jsp" %>
<c:url value="/admin/create-book" var="createBookURL"/>

<div class="bg_breadcrumbs z-depth-1">
    <div class="container">
        <div class="breadcrumbs clearfix">
            <a class="breadcrumb-link" href="<c:url value="/"/>"><spring:message code="breadcrumb.home"/></a>
            <c:choose>
                <c:when test="${not empty book.id}">
                    <a class="breadcrumb-link" href="<c:url value="/books"/>"><spring:message code="title.books"/></a>
                    <span>Редактиране на ${book.title}</span>
                </c:when>
                <c:otherwise>
                    <a class="breadcrumb-link" href="<c:url value="/admin/menu"/>"><spring:message code="title.administration.module"/></a>
                    <span> <spring:message code="title.create.book"/></span>
                </c:otherwise>
            </c:choose>
        </div>
    </div>
</div>

<div class="container main-content">
    <div class="z-depth-2 white mT2em p50px">
        <img width="70" height="70" class="right mT-15px" src="<c:url value="/resources/images/open-book.png"/>"/>
        <div class="section-title">
            <c:choose>
                <c:when test="${not empty book.id}">
                    Редактиране на ${book.title}
                </c:when>
                <c:otherwise>
                    <spring:message code="title.create.book"/>
                </c:otherwise>
            </c:choose>
        </div>
        <div>
            <form:form id="create-book-form" cssClass="col s12" modelAttribute="book" action="${createBookURL}" method="post" enctype="multipart/form-data">
                <div class="row float-left mB0">
                    <div class="input-field col">
                        <label id="cover-image-label" for="image-file" class="custom-file-upload mB1em cover-image-label
                           <c:if test="${not empty book.cover.filename}"><c:out value="remove-pb"/></c:if>">
                            <c:choose>
                                <c:when test="${not empty book.cover.filename}">
                                    <img id="cover-image"
                                         src='<c:out value="data:image/jpg;base64,${book.cover.encodedContent}"/>'
                                         class="cover-image">
                                </c:when>
                                <c:otherwise>
                                    <div class="cover-text"><spring:message code="label.cover"/></div>
                                </c:otherwise>
                            </c:choose>
                        </label>
                        <input class="display-none" type="file" name="imageFile" id="image-file" />
                    </div>
                </div>
                <div class="row mB0">
                    <div class="input-field col">
                        <label id="book-file-label" for="book-file" class="custom-file-upload mB1em book-file-label
                        <c:if test="${not empty book.file.filename}"><c:out value="remove-pb"/></c:if>">
                            <c:choose>
                                <c:when test="${not empty book.file.filename}">
                                    <img src="<c:url value="/resources/images/if_pdf_65920.png"/>"/>
                                    <p class="w500px"><c:out value="${book.file.filename}"/></p>
                                </c:when>
                                <c:otherwise>
                                    <div class="align-center mT30px"><spring:message code="label.file"/></div>
                                </c:otherwise>
                            </c:choose>
                        </label>
                        <input class="display-none" type="file" name="bookFile" id="book-file" />
                        <div class="m_T5px" id="book-file-error-msg">
                            <form:errors path="file.filename" cssClass="message-error"/>
                        </div>
                    </div>

                </div>
                <div class="clear" id="image-file-error-msg">
                    <form:errors path="cover.filename" cssClass="message-error"/>
                </div>
                <div class="row">
                    <div class="input-field  col s4">
                        <input type="text" id="new-book-title" name="title" value="${book.title}">
                        <label for="new-book-title" class=""><spring:message code="label.title"/></label>
                        <form:errors path="title" cssClass="message-error"/>
                    </div>
                    <div class="input-field  col s4 ">
                        <input type="text" id="new-book-author" name="author" value="${book.author}">
                        <label for="new-book-author" class=""><spring:message code="label.author"/></label>
                        <form:errors path="author" cssClass="message-error"/>
                    </div>
                    <div class="input-field  col s4 ">
                        <input type="text" id="new-book-year" name="year" value="${book.year}">
                        <label for="new-book-year" class=""><spring:message code="label.year"/></label>
                        <form:errors path="year" cssClass="message-error"/>
                    </div>
                </div>
                <div class="row mB0">
                    <div class="input-field  col s4">
                        <input type="text" id="new-book-isbn" name="isbn" value="${book.isbn}">
                        <label for="new-book-year" class=""><spring:message code="label.isbn"/></label>
                        <form:errors path="isbn" cssClass="message-error"/>
                    </div>
                    <div class="input-field col s4">
                        <select name="category.id">
                            <c:forEach var="category" items="${categories}">
                                <option value='${category.id}'
                                        <c:if test="${category.id eq book.category.id}">
                                            <c:out value="selected='selected'"/>
                                        </c:if>
                                >${category.name}</option>
                            </c:forEach>
                        </select>
                        <label><spring:message code="label.category"/></label>
                        <form:errors path="category.id" cssClass="message-error"/>
                    </div>
                    <div class="input-field col s4">
                        <select name="language.id">
                            <c:forEach var="language" items="${languages}">
                                <option value='${language.id}'
                                        <c:if test="${language.id eq book.language.id}">
                                            <c:out value="selected='selected'"/>
                                        </c:if>
                                >${language.name}</option>
                            </c:forEach>
                        </select>
                        <label><spring:message code="label.language"/></label>
                        <form:errors path="language.id" cssClass="message-error"/>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 custom-textarea">
                        <textarea id="new-book-description" name="description" class="materialize-textarea"
                                  data-length="2000">${book.description}</textarea>
                        <label for="new-book-description"><spring:message code="label.short.descripition"/></label>
                        <form:errors path="description" cssClass="message-error"/>
                    </div>
                </div>
                <div>
                    <button type="submit" class="waves-effect waves-light btn light-blue darken-4">
                        <i class="material-icons left">check</i><spring:message code="btn.save"/>
                    </button>
                </div>
                <input type="hidden" name="id" value="${book.id}">
            </form:form>
        </div>
    </div>

</div>
<%@ include file="../common/footer.jsp" %>

<script src='<c:url value="/resources/js/create-book.js"/>' type="text/javascript"></script>

src/main/webapp/WEB-INF/view/admin/view.jsp
<%--
  Created by IntelliJ IDEA.
  User: denislav.veizov
  Date: 23.1.2018 г.
  Time: 16:23
  To change this template use File | Settings | File Templates.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="../common/header.jsp" %>
<div class="bg_breadcrumbs hidden-xs hidden-sm">
    <div class="container">
        <div class="breadcrumbs clearfix">
            <a class="breadcrumb-link" href="<c:url value="/"/>"><spring:message code="breadcrumb.home"/></a>
        </div>
    </div>
</div>

<div class="container main-content">
TEST
</div>
<%@ include file="../common/footer.jsp" %>